version: '3'

services:
  etl:
    container_name: etl
    restart: unless-stopped
    build: ./etl
    env_file:
      - .env
    depends_on:
      - postgres
      - es
    networks:
      - my_network

  postgres:
    image: postgres:13
    container_name: postgres_sprint_3
    restart: unless-stopped
    volumes:
      - ./.data/postgres:/data/postgres
      - ./dump.sql:/docker-entrypoint-initdb.d/dump.sql:ro
    environment:
      POSTGRES_DB: ${DB_NAME:-movies_database}
      POSTGRES_USER: ${DB_USER:-app}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-password}
    ports:
      - "5432:5432"
    networks:
      - my_network

  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.6.2
    container_name: es
    restart: unless-stopped
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms4096m -Xmx4096m
    ports:
      - "9200:9200"
    networks:
      - my_network

networks:
  my_network:
    external: True
