version: '3'

services:
  web:
    build: .
    volumes:
      - static_volume:/opt/app/static/
    env_file:
      - ./app/config/.env
    depends_on:
      - db
    networks:
      - my_network

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./etc/postgres/default-init.sql:/docker-entrypoint-initdb.d/default-init.sql
    env_file:
      - ./app/config/.env
    networks:
      - my_network
  
  nginx:
    container_name: nginx
    image: nginx:alpine
    volumes:
      - ./etc/nginx:/etc/nginx/conf.d:ro
      - ./data:/data/:ro
      - static_volume:/app/static/
      - media_volume:/app/media/
    depends_on:
      - web
    ports:
      - "80:80"
    networks:
      - my_network
  
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.6.2
    restart: always
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
    networks:
      - my_network
  
  postgres_to_es:
    container_name: postgres_to_es
    build: ./postgres_to_es
    restart: always
    env_file:
      - ./app/config/.env
    depends_on:
      - elasticsearch
      - db
    networks:
      - my_network


volumes:
  postgres_data:
  static_volume:
  media_volume:

networks:
  my_network: